apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: wednesday-java-web-app-team2
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: wednesday-java-web-app-team2
  namespace: jeremy
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: scanning_source_policy
    value: lax-scan-policy
  - name: scanning_image_policy
    value: lax-scan-policy
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: java
      apps.tanzu.vmware.com/pipeline: test
  source:
    git:
      url: https://github.com/x95castle1/wednesday-java-web-app
      ref:
        branch: team2
